version: '3.2'
services:
  springapp:
    image: 192.168.100.101:8088/mongo-db:latest
    depends_on:
      - mongo
    ports:
      - 7070:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@123
    networks:
      - springnetwork
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
      - mongodbvol:/data/db
    networks:
      - springnetwork


volumes:
  mongodbvol:
    driver: local

networks:
  springnetwork:
    driver: bridge
